### PR TITLE
cp-370: Change font color

### PR DESCRIPTION
**Pull request by vladyslavdobychin**
As was mentioned in the [issue](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/370) changed all instances of color #000000 to #302E36 (--gray-400)

### CODE REVIEW

**Review by Ekit18 — DISMISSED** [review]

**Review by OlenaYatseniuk — DISMISSED** [review]

**Comment by fshabanov** [comment]
@vladyslavdobychin have you tried to update the default text color instead of setting the new color everywhere?

**Comment by vladyslavdobychin** [comment]
> @vladyslavdobychin have you tried to update the default text color instead of setting the new color everywhere?

I've been thinking about that, but I saw multiple occasion of text being colored differently, like text of a button or text inside of the add file modal. I was just trying to avoid making changes somewhere I wasn't supposed to.

**Comment by vladyslavdobychin** [comment]
@fshabanov and how would you advise to do this?

**Comment by liza-veis** [comment]
We should set it in global styles, but also for such components as input, button, textarea we should set it one more time

**Review by liza-veis — APPROVED** [review]

**Review by v0ldemar01 — APPROVED** [review]

**Pull request merged**
