### PR TITLE
cp-161: Fix the modal display on mobile

### PR DESCRIPTION
**Pull request by vladyslavdobychin**
Fixed the [issue](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/161#issuecomment-1733327900) of displaying the modal window with a timer on mobile screens  

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/f8683dc2-cd10-49b6-ac30-789ba53607e2

### CODE REVIEW

**Comment by dmytro-kucherenko** [comment]
How will it look like with width at 320 px as it's our bottom bar? The modal without paddings on sides looks quite weird for me

**Comment by Xxandder** [comment]
And as for me it would be better if we make 2 or 4 rows of durations on mobile, but I am not sure whether it fits the design

**Comment by vladyslavdobychin** [comment]
> How will it look like with width at 320 px as it's our bottom bar? The modal without paddings on sides looks quite weird for me

You are right, and honestly I wan't sure what to do with it. 
The timer has too many elements, I tried making the gap between buttons even smaller and the more screen shrinks the more weird it looks. 
Stacking buttons in column felt unholy   


https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/4235a925-dc4c-40e4-bc2b-2137260aaa31

**Comment by vladyslavdobychin** [comment]
> And as for me it would be better if we make 2 or 4 rows of durations on mobile, but I am not sure whether it fits the design

That's the fun part, mister Oleksandr, there is no design. But two rows sound like something not-that-bad

**Comment by vladyslavdobychin** [comment]
Gentlemen,
@Dmytro-Kucherenko @Xxandder 
I tried stacking buttons in two rows and added a thin margin around the modal to make sure it stays within the screen. What do you think? 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/9f47c205-3a48-45e7-b38d-de0f09e6f58b

**Comment by Xxandder** [comment]
> Gentlemen, @Dmytro-Kucherenko @Xxandder I tried stacking buttons in two rows and added a thin margin around the modal to make sure it stays within the screen. What do you think?
> 
>  Screen.Recording.2023-09-26.at.12.54.34.mov

as for me it's better to have simmilar number of durations on each row. But in case if the number is odd like 3 or 5 - it shoud have griid like 2*2*1

**Comment by Xxandder** [comment]
And I think you can make durations bigger in this case to make interaction with them more comfortable

**Comment by vladyslavdobychin** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/7b30d10a-6e2e-4d05-85f4-8c3bc3a6f2c2

**Review by OlenaYatseniuk — APPROVED** [review]

**Review by HIMDanny — APPROVED** [review]

**Review by liza-veis — APPROVED** [review]

**Review by dmytro-kucherenko — APPROVED** [review]
It's a good one)

**Review by Xxandder — APPROVED** [review]
Looks cool!

**Review by v0ldemar01 — APPROVED** [review]

**Pull request merged**
